@host=http://localhost:5018

POST {{host}}/payments/create
Content-Type: application/json

{
    "customerId": "a924b1b4-3437-4ce7-8c60-09d475ab7af0",
    "orderId": "02b1e841-c57a-4a12-96b5-fa4f5a3f504c",
    "paymentMethod": "pm_card_visa",
    "amount": 300
}