@host=http://localhost:5018
@productId=64010e3c-766a-45a5-948f-e8d14735ed8c
@imageId=d05dd3ae-148b-4d83-ba06-4a6c213fdd3a

### Add product image
PUT {{host}}/product/{{productId}}/updateImage/{{imageId}}
Content-Type: application/json

{
    "url": "tes the upadte image url",
    "alt": "image alt",
    "title": "product image 2",
    "contentType": "image jpg"
}


