@host=http://localhost:5018

POST {{host}}/transporter/register
Content-Type: application/json

{
    "companyName": "Company Name",
    "description": "Description",
    "AddressRequest": {
        "city": "City",
        "zipCode": "Zip Code"
    }
}