version: '3.8'

services:
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: sinus707/serverimage:1.0 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5176:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sinus707/frontendimage:1.0 
    volumes:
      - frontend_build:/app/build  # Mount build output to named volume
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build:/usr/share/caddy  # Ensure this is the same volume
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:
  frontend_build:

networks:
  app-network:
    driver: bridge
