version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: sinus707/serverimage:2.0 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5176:8080"
    networks:
      - app-network

  caddy:
    build:
      context: ./frontend 
    image: sinus707/caddyimage:2.0 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge