version: '3.8'

services:
  backend:
    image: "${backend_IMAGE}"
    ports:
      - "8000:80"

  frontend:
    image: "${frontend_IMAGE}"
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true