@host=http://localhost:5018

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWQyNDRkOS1kYWFmLTQxMWUtOGE4NC1hZDIwNGFmNDkxZWYiLCJnaXZlbl9uYW1lIjoiTGFycyIsImZhbWlseV9uYW1lIjoiTGFyc2VuIiwiZW1haWwiOiJMYXJzQHVpYS5ubyIsImp0aSI6ImI2NmY3ODI2LTY2NzgtNGUxMy1hZDZlLTZmN2I2YjNiODg1MCIsImV4cCI6MTcxMjMxODkxMiwiaXNzIjoiTG9rYWxQcm9kdXNlcnQiLCJhdWQiOiJMb2thbFByb2R1c2VydCJ9.Li_44O4gD80VsbfNcz5ypLyjDnRcT6Bf4AneRzqaFm0

POST {{host}}/admin/asignRoleToUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": "c5d244d9-daaf-411e-8a84-ad204af491ef",
    "email": "Ole@uia.no",
    "role": "Produser"
}

